services:
  db:
    image: postgres:16
    container_name: tick_marketing_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tick_marketing_saas
    ports:
      - "5432:5432"
    volumes:
      - tick_marketing_db:/var/lib/postgresql/data
volumes:
  tick_marketing_db:
